# Generated by Django 6.0 on 2025-12-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Task Categories'},
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='icon_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
